import "@fortawesome/fontawesome-free/css/all.min.css";
import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import { ChakraProvider } from "@chakra-ui/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Header />
          {children}
          <Footer />
        </ChakraProvider>
      </body>
    </html>
  );
}
