import "@fortawesome/fontawesome-free/css/all.min.css";
// import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import { ChakraProvider } from "@chakra-ui/react";
import Header from "@/components/Header/Header";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ChakraProvider>
            <Header />
            {children}
            <Footer />
          </ChakraProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
